<a href="https://colab.research.google.com/github/alimoradi296/DeepLearning/blob/main/AnnCLassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ANN








##Datapreprocessing Template

###importing the Libraries

In [ ]:
import pandas as pd
import numpy as np

###importing dataset

In [ ]:
df=pd.read_csv("/content/sample_data/Churn_Modelling.csv")

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
df1=df.drop(columns=['RowNumber','CustomerId','Surname','Exited'])
y=df.Exited

In [ ]:
df1

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

### Category Encoding


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [ ]:
le=LabelEncoder()
df1.Gender=le.fit_transform(df1.Gender)

In [ ]:
df2=df1.values

In [ ]:
ohEncoder=OneHotEncoder()

In [ ]:
columnTransformer=ColumnTransformer([('onehotencoder',ohEncoder,[1])],remainder='passthrough')

In [ ]:
X=np.array(columnTransformer.fit_transform(df2))

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Split Train and Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=15)

In [ ]:
y_train.shape

(8000,)

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

###Feature Scaling


In [ ]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [ ]:
X_train

array([[ 0.99950012, -0.58196914, -0.57234647, ...,  0.6420125 ,
        -1.03227043,  1.00833475],
       [-1.00050013, -0.58196914,  1.74719344, ...,  0.6420125 ,
        -1.03227043, -0.77300966],
       [-1.00050013, -0.58196914,  1.74719344, ..., -1.55760207,
        -1.03227043,  1.72489478],
       ...,
       [ 0.99950012, -0.58196914, -0.57234647, ..., -1.55760207,
        -1.03227043, -1.67575833],
       [ 0.99950012, -0.58196914, -0.57234647, ...,  0.6420125 ,
        -1.03227043, -1.20846462],
       [ 0.99950012, -0.58196914, -0.57234647, ...,  0.6420125 ,
         0.9687384 ,  0.55450141]])

## Building the ANN




### import libraries

In [ ]:
import tensorflow as tf
from tensorflow import keras

### Add Layers

In [ ]:
model=keras.Sequential()
model.add(keras.layers.Dense(units=6,activation='relu'))
model.add(keras.layers.Dense(units=8,activation='relu'))
model.add(keras.layers.Dense(units=1,activation='sigmoid'))


## Training the Model

### Compiling Model


In [ ]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0001),loss='binary_crossentropy',
              metrics=['accuracy'])

### Training the Model

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 [==============================] - 1s 2ms/step - loss: 0.9260 - accuracy: 0.2453
Epoch 2/50
130/250 [==============>...............] - ETA: 0s - loss: 0.7939 - accuracy: 0.3481

## Predictiong and Evaluting

In [ ]:
y_pred=(model.predict(X_test)>0.5)

### Making the  Confusion Matrix


In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)